version: '3.9'

services:
  postgres-inventory:
    image: postgres
    ports:
      - "5434:5432"
    container_name: postgres-inventory
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=inventory-service
    volumes:
      - ./data/inventory:/var/lib/postgresql/data
      - ./init/inventory/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - multi-net

#  postgres:
#        image: postgres
#        ports:
#          - "5433:5432"
#        container_name: postgres-single
#       environment:
#          - POSTGRES_USER=admin
#         - POSTGRES_PASSWORD=password
#        volumes:
#          - ./data/order:/var/lib/postgresql/data
#          - ./init/order/init.sql:docker-entrypoint-initdb.d/init.sql

  postgres-orders:
    image: postgres
    ports:
      - "5433:5432"
    container_name: postgres-order
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/order:/var/lib/postgresql/data
      - ./init/order/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - multi-net

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    container_name: pgadmin-single
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - multi-net

volumes:
  postgres:
    driver: localS


networks:
  multi-net:
    driver: bridge